services:
  mc:
    image: itzg/minecraft-server
    # command: --forceUpgrade --eraseCache
    env_file:
      - ../../.env
    ports:
    # expose the Minecraft server port outside of container
    - "25565:25565"
    - "25575:25575"
    - "24454:24454/udp" # Simple Voice Chat mod
    - "8100:8100" # BlueMap
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
     
      RCON_PASSWORD: ${RCON_PASSWORD}
      DEBUG: "true"

      MEMORY: 18G
      MAX_MEMORY: 20G
        
      VERSION: "1.20.1"
      MODS_FILE: /extras/mods.txt

      OVERRIDE_SERVER_PROPERTIES: "TRUE"

      SERVER_NAME: "${SERVER_NAME:-Minecraft Server}"
      MOTD: "${MOTD:-Welcome to the Minecraft Server! Explore and have fun!}"
      SEED: "${SEED:-}"
      DIFFICULTY: "hard"
      PVP: "true"
      MODE: "survival"

      MAX_PLAYERS: 15
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ONLINE_MODE: false

      SIMULATION_DISTANCE: 12
      VIEW_DISTANCE: 30
     
      MAX_TICK_TIME: -1

      SPAWN_PROTECTION: 0

      OPS_FILE: /extras/ops.json
    depends_on:
      restore-backup:
        condition: service_completed_successfully
    volumes:
      # use a named, managed volume for data volume
      - 1204_mc_forge:/data
      - ./mods:/mods:ro
      - ./extras:/extras:ro
    restart: unless-stopped

  restore-backup:
    image: itzg/mc-backup
    user: "1000"
    restart: no
    entrypoint: restore-rsync-backup
    volumes:
      - 1204_mc_forge:/data
      - ./backups:/backups:ro

  backups:
    image: itzg/mc-backup
    user: "1000"
    env_file:
      - ../../.env
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_METHOD: rsync
      BACKUP_INTERVAL: "12h"
      INITIAL_DELAY: "2m"

      RCON_HOST: mc

      PRUNE_BACKUPS_COUNT: 10
      PRUNE_BACKUPS_DAYS: 30      
    volumes:
      - 1204_mc_forge:/data:ro
      - ./backups:/backups
volumes:
  # declared the named volume, but use default/local storage engine
  1204_mc_forge: {}