packages:
  - modpacks/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.2

  # Misc
  zod: ^3.24.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
