version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    env_file:
      - .env
    ports:
      - "25565:25565"
      - "25575:25575"
      - "24454:24454/udp"
      - "8100:8100"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      RCON_PASSWORD: ${RCON_PASSWORD}
      DEBUG: "true"
      MEMORY: 18G
      MAX_MEMORY: 20G
      VERSION: "1.20.1"
      MODS_FILE: /extras/mods.txt
      DATAPACKS_FILE: /extras/datapacks.txt
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "${SERVER_NAME:-Minecraft Server}"
      MOTD: "${MOTD:-Welcome to the Minecraft Server! Explore and have fun!}"
      SEED: "${SEED:-}"
      DIFFICULTY: "hard"
      PVP: "true"
      MODE: "survival"
      MAX_PLAYERS: 15
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ONLINE_MODE: false
      SIMULATION_DISTANCE: 6
      VIEW_DISTANCE: 16
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      OPS_FILE: /extras/ops.json
    volumes:
      - mc_forge:/data
      - ./mods:/mods:ro
      - ./extras:/extras:ro
    restart: unless-stopped

  backups:
    image: itzg/mc-backup
    user: "1000"
    env_file:
      - .env
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_METHOD: rsync
      PRUNE_BACKUPS_COUNT: 10
      PRUNE_BACKUPS_DAYS: 30
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      INITIAL_DELAY: 0
    volumes:
      - ./mc_forge:/data:ro
      - backups:/backups

volumes:
  mc_forge: {}
  backups: {}
