services:
  mc:
    image: itzg/minecraft-server
    # command: --forceUpgrade --eraseCache
    env_file:
      - .env
    ports:
    # expose the Minecraft server port outside of container
    - "25565:25565"
    - "25575:25575"
    - "24454:24454/udp" # Simple Voice Chat mod
    - "8100:8100" # BlueMap
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
     
      RCON_PASSWORD: ${RCON_PASSWORD}
      DEBUG: "true"

      MEMORY: 18G
      MAX_MEMORY: 20G
        
      VERSION: "1.20.1"
      MODS_FILE: /extras/mods.txt
      DATAPACKS_FILE: /extras/datapacks.txt

      OVERRIDE_SERVER_PROPERTIES: "TRUE"

      SERVER_NAME: "${SERVER_NAME:-Minecraft Server}"
      MOTD: "${MOTD:-Welcome to the Minecraft Server! Explore and have fun!}"
      SEED: "${SEED:-}"
      DIFFICULTY: "hard"
      PVP: "true"
      MODE: "survival"

      MAX_PLAYERS: 15
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ONLINE_MODE: false

      SIMULATION_DISTANCE: 6
      VIEW_DISTANCE: 16
     
      MAX_TICK_TIME: -1

      SPAWN_PROTECTION: 0

      OPS_FILE: /extras/ops.json
    volumes:
      # use a named, managed volume for data volume
      - mc_forge:/data
      - ./mods:/mods:ro
      - ./extras:/extras:ro
    restart: unless-stopped
volumes:
  # declared the named volume, but use default/local storage engine
  mc_forge: {}