services:
  mc:
    # FTBA support is only available in non-Alpine images
    image: itzg/minecraft-server:java21
    env_file:
      - .env
    ports:
      # expose the Minecraft server port outside of container
      - 25565:25565
      - "25575:25575"
      - "24454:24454/udp" # Simple Voice Chat mod
    environment:
      # REQUIRED for all types
      EULA: "TRUE"

      RCON_PASSWORD: ${RCON_PASSWORD}
      DEBUG: "true"

      MEMORY: 18G
      MAX_MEMORY: 20G

      MAX_PLAYERS: 15
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ONLINE_MODE: false

      SIMULATION_DISTANCE: 6
      VIEW_DISTANCE: 16
     
      MAX_TICK_TIME: -1

      SPAWN_PROTECTION: 0

      # Use Pack ID from https://ftb.neptunepowered.org/pack/ftb-presents-direwolf20-1-12/
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: fantasy-minecraft-fabric

      MODS_FILE: /extras/mods.txt
    volumes:
      - mc-data:/data
    restart: unless-stopped

volumes:
  mc-data: {}