services:
  mc:
    # FTBA support is only available in non-Alpine images
    image: itzg/minecraft-server:java17
    ports:
      # expose the Minecraft server port outside of container
      - 25565:25565
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      TYPE: FTBA
      # Use Pack ID from https://ftb.neptunepowered.org/pack/ftb-presents-direwolf20-1-12/
      FTB_MODPACK_ID: "119"
      FTB_MODPACK_VERSION_ID: "12252"
    volumes:
      - ftb:/data

volumes:
  ftb: {}